name: dart_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.0
  
dependencies:
  http: ^0.13.5
